=== corysterling/corysterling.github.com/xml/engagements.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="engagements">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="gig" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="venue" type="xs:string" />
            <xs:element name="details" type="xs:string" />
            <xs:element name="date" type="xs:string" />
            <xs:element name="time" type="xs:string" />
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== corysterling/corysterling.github.com/xml/gigs.xml
<?xml version="1.0"?>

<engagements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="engagements.xsd">

  <gig>
    <venue>Parilla Steakhouse (137th and Broadway)</venue>
    <details>Cory Sterling B3 Trio w/ Christian N. and Rick Cragin</details>
    <date>Sun Sep 22</date>
    <time>7:30-11:00pm</time>
  </gig>

  <gig>
    <venue>Miles Cafe (212 E. 52nd St. 3Fl. Between 2nd/3rd Ave.)</venue>
    <details>w/ Chris Davidson Band</details>
    <date>Sat Sep 16</date>
    <time>8:30-10:00pm</time>
  </gig>

</engagements>
